### ISSUE TITLE
Error installing erpnext_demo 

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext_demo#10]
ubuntu@ip-172-31-27-142:~$ bench --site mytest.agtech.com.sg install-app erpnext_demo
Installing erpnext_demo...
Complete Setup...
/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/demo_docs/Sales Taxes and Charges Template.json missing
/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/demo_docs/Purchase Taxes and Charges Template.json missing
Simulating 2015-01-14
Simulating 2015-01-15
Simulating 2015-01-23
Simulating 2015-02-04Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 77, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/installer.py", line 130, in install_app
    frappe.get_attr(after_install)()
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/utils.py", line 31, in make_demo
    erpnext_demo.make_demo.make()
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 24, in make
    simulate()
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/simulate.py", line 52, in simulate
    run_manufacturing(current_date)
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/manufacturing.py", line 29, in run_manufacturing
    b.submit()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 518, in submit
    self.save()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in save
    self.run_post_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 562, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 507, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 621, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 604, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 501, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 147, in on_submit
    self.make_time_logs()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/production_order/production_order.py", line 229, in make_time_logs
    time_log.save()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 214, in save
    self.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 176, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 541, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 507, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 621, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 604, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 501, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/projects/doctype/time_log/time_log.py", line 25, in validate
    self.validate_production_order()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/projects/doctype/time_log/time_log.py", line 127, in validate_production_order
    frappe.throw(_("You can make a time log only against a submitted production order"), NotSubmittedError)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 252, in throw
    msgprint(msg, raise_exception=exc)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 245, in msgprint
    _raise_exception()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 230, in _raise_exception
    raise raise_exception, encode(msg)
erpnext.projects.doctype.time_log.time_log.NotSubmittedError: You can make a time log only against a submitted production order

**Comment by justinlusg** [comment]
Not fixed yet
