### ISSUE TITLE
[Error] Serialized Item Wind Mill A Series cannot be updated using Stock Reconciliation

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext_demo#28]
```
Simulating 2016-02-26Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/commands.py", line 151, in reinstall
    _new_site(frappe.conf.db_name, site, verbose=context.verbose, force=True, reinstall=True, install_apps=installed)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/commands.py", line 97, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/installer.py", line 134, in install_app
    frappe.get_attr(after_install)()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext_demo/erpnext_demo/utils.py", line 31, in make_demo
    erpnext_demo.make_demo.make()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py", line 20, in make
    simulate()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext_demo/erpnext_demo/simulate.py", line 53, in simulate
    run_stock(current_date)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext_demo/erpnext_demo/stock.py", line 17, in run_stock
    make_stock_reconciliation(current_date)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext_demo/erpnext_demo/stock.py", line 73, in make_stock_reconciliation
    stock_reco.insert()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 193, in insert
    self.run_before_save_methods()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 617, in run_before_save_methods
    self.run_method("validate")
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 579, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 718, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/frappe/frappe/model/document.py", line 573, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 28, in validate
    self.validate_data()
  File "/Users/anandpdoshi/dev/work/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py", line 128, in validate_data
    raise frappe.ValidationError(self.validation_messages)
frappe.exceptions.ValidationError: [u'Row # 1: Serialized Item Wind Mill A Series cannot be updated \t\t\t\t\tusing Stock Reconciliation']
```

**Comment by vjFaLk** [comment]
Ref : Master branch
