### ISSUE TITLE
Error when trying to run install-app on erpnext v5

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext_demo#9]
Error when trying to run install-app on erpnext v5

ubuntu@ip-172-31-27-142:~$ bench --site mytest.agtech.com.sg install-app erpnext                        _demo
Installing erpnext_demo...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", lin                        e 77, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", lin                        e 14, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/click/co                        re.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 28, in _                        func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands.py", line 163, in                         install_app
    _install_app(app, verbose=context.verbose)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/installer.py", line 117, in                         install_app
    frappe.get_attr(before_install)()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 725, in                         get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 555, in                         get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/utils.py", line                         7, in <module>
    import erpnext_demo.make_demo
  File "/home/ubuntu/frappe-bench/apps/erpnext_demo/erpnext_demo/make_demo.py",                         line 8, in <module>
    from frappe.widgets import query_report
ImportError: No module named widgets
ubuntu@ip-172-31-27-142:~$

**Comment by pdvyas** [comment]
This is because v5.0 branch is not merged to master. There is one issue
with the demo, will merge after it's fixed.

**Comment by pdvyas** [comment]
Try,
```
bench update
bench --site mytest.agtech.com.sg reinstall
```
